
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class MijnVenster extends javax.swing.JFrame {

    /**
     * Creates new form MijnVenster
     */
    public MijnVenster() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        randomArray = new int[9];
        fillRandomArray();
  	
        CenterPaneel.setLayout(new GridLayout(3,3,3,3));
  	knoppenGrid = new JButton[3][3];
  	for(int rij=0;rij<3;rij++)
  	{
  		for(int kol=0;kol<3;kol++)
  		{
  			knoppenGrid[rij][kol]=maakKnop(CenterPaneel , rij, kol);
  			btnID++;
  		}
  	}
        
        CenterPaneel.doLayout(); 
        
    }
    
    
    
    public JButton maakKnop(JPanel p , int rij, int kol)
  {
                System.out.println(""+randomArray[btnID]);
  		int iValue = randomArray[btnID];
  		JButton knop = new JButton(""+iValue);
                
                knop.setFont(new java.awt.Font("Trebuchet MS", 1, 40));
                knop.setBackground(Color.BLACK);
                knop.setForeground(Color.YELLOW);
                
  		p.add(knop);
                System.out.println("knop");
  		return(knop);
  }
  
   public void fillRandomArray()
  {
  	
  				for (i = 0; i<randomArray.length ; i++)
  				{
  					
  				do
  				{
  					getal = (int) (10*Math.random());
                                            if(getal==0)
                                                        {
      								i0++;
      								iCount = i0;
                                                
                                                        }
                                                else if (getal == 1) 
      							{
      								i1++;
      								iCount = i1;
      							}
      						else if (getal == 2) 
      							{
      								i2++;
      								iCount = i2;
      							}
      						else if (getal == 3) 
      							{
      								i3++;
      								iCount = i3;
      							}
      						else if (getal == 4) 
      							{
      								i4++;
      								iCount = i4;
      							}
      						else if (getal == 5) 
      							{
      								i5++;
      								iCount = i5;
      							}
      						else if (getal == 6) 
      							{
      								i6++;
      								iCount = i6;
      							}
      						else if (getal == 7) 
      							{
      								i7++;
      								iCount = i7;
      							}
      						else if (getal == 8) 
      							{
      								i8++;
      								iCount = i8;
      							}
      						else if (getal == 9) 
      							{
      								i9++;
      								iCount = i9;
      							}
      						
      							
  				} while (iCount > 1);
                                    System.out.println(""+getal);
  					randomArray[i] = getal;

                                }
  				
  	
  	
  	
  }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CenterPaneel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout CenterPaneelLayout = new javax.swing.GroupLayout(CenterPaneel);
        CenterPaneel.setLayout(CenterPaneelLayout);
        CenterPaneelLayout.setHorizontalGroup(
            CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        CenterPaneelLayout.setVerticalGroup(
            CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CenterPaneel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CenterPaneel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MijnVenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MijnVenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MijnVenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MijnVenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MijnVenster().setVisible(true);

            }
        });
    }

    
                int i0 = 2;
      		int i1 = 0;
      		int i2 = 0;
      		int i3 = 0;
      		int i4 = 0;
      		int i5 = 0;
      		int i6 = 0;
      		int i7 = 0;
      		int i8 = 0;
      		int i9 = 0;
      		int iCount = 0;
    		private int [] randomArray;
    		int getal;
  		int btnID = 0;
    		private JButton [][] knoppenGrid;
                int i=0;
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPaneel;
    // End of variables declaration//GEN-END:variables
}
