
import java.awt.Color;
import java.awt.Graphics;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class MijnVenster1 extends javax.swing.JFrame {

    /**
     * Creates new form MijnVenster1
     */
    public MijnVenster1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MijnPaneel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        MijnPaneel.setBackground(new java.awt.Color(0, 0, 0));
        MijnPaneel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Geef een weerstand die naar E12 reeks waarde moet omgezet worden en druk dan op <ENTER>");

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });

        lblResult.setForeground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout MijnPaneelLayout = new javax.swing.GroupLayout(MijnPaneel);
        MijnPaneel.setLayout(MijnPaneelLayout);
        MijnPaneelLayout.setHorizontalGroup(
            MijnPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MijnPaneelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MijnPaneelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        MijnPaneelLayout.setVerticalGroup(
            MijnPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MijnPaneelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(MijnPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MijnPaneel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MijnPaneel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
        Graphics g = MijnPaneel.getGraphics(); 
        // g.clearRect (0,0,1000,1000); 
        restArray = new double[12];
        int iCount = 0;
        double inputValue = Double.parseDouble(txtInput.getText());
        if (inputValue > 91)
        {
                do{
                    inputValue = inputValue / 10;
                    iCount++;
                        
                    } while (inputValue < 9.1 | inputValue > 91 );            
            
        }
        else if (inputValue < 9.1)
        {
                    do{
                      inputValue = inputValue * 10;
                      iCount--;
                      System.out.println(iCount);
                      } while (inputValue < 9.1 | inputValue > 91 );                     
                    
        }

        
        
        double rest;
        double prevRest = 92;
        int pos = 0;
        for (int i =0; i<e12.length ; i++){
            rest = Math.abs(e12[i] - inputValue);
            System.out.println("rest " + i + " : " + rest);
            restArray[i] = rest;
            
            if (rest < prevRest)
            {
                prevRest = rest;
                pos = i;
            }
        }

        
        
        double weerstandWaarde = e12[pos];
        System.out.println("weerstandWaarde " + weerstandWaarde);
        
        
              
        
        
        
        

        //txtInput.setText(""+weerstandWaarde);
        
        
        
        
        
        
        //weerstandWaarde = ((int) Math.round(weerstandWaarde)) ;
        System.out.println("pow " +  Math.pow(10,iCount));
        weerstandWaarde = weerstandWaarde * Math.pow(10,iCount);      
        
        String result = "Hier is een weerstand van " + weerstandWaarde + " \u03A9 voor nodig";
        g.setColor(Color.BLUE);
        g.drawLine(150, 350, 200, 350);
        g.drawRect(200,300,400,100);
        g.drawLine(600, 350, 650, 350);
        g.setColor(Color.WHITE);
        
        lblResult.setText(result);
        
        int weerstandWaarde2 = (int) weerstandWaarde;
        String str = "" + weerstandWaarde2;
        
        System.out.println(weerstandWaarde2);
        
       String firstValue = str.substring(1,1);
        
       
       
            g.fillRect(300, 300, 50, 100);
            
        
        
        
        
        
        g.fillRect(375, 300, 50, 100);
        g.fillRect(450, 300, 50, 100);
        
        
        
    }//GEN-LAST:event_txtInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MijnVenster1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MijnVenster1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MijnVenster1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MijnVenster1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MijnVenster1().setVisible(true);
            }
        });
    }

    
    int[] e12= {10,12,15,18,22,27,33,39,47,56,68,82};
    double[] restArray;
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MijnPaneel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
