

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class MijnVenster extends javax.swing.JFrame {

    /**
     * Creates new form MijnVenster
     */
    public MijnVenster() {
        initComponents();
        
        
          // thread instantie maken en starten
	klokje = new Klokske();
	klokje.start();
        lijst = new ArrayList<>();
        
        txtDatabase.setText("Naam" + "\t" + "Klas" + "\t" + "Jaar" + "\n" + "====" + "\t" + "====" + "\t" + "====" );
        txtNaam.setText("David");
        txtKlas.setText("2PB-ICT");
        txtJaar.setText("1977");
        
        
        
        
            
        
        txtNaam.requestFocusInWindow();
        
        String username = System.getProperty("user.name");
        lblUsername.setText(""+username);
        
            repaint();
            
            
            
            
            
            
            
            
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NoordPaneel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ZuidPaneel = new javax.swing.JPanel();
        lblUur = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblUur1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblUur2 = new javax.swing.JLabel();
        RechtsPaneel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtServer = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        btnStartServer = new javax.swing.JButton();
        CenterPaneel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatabase = new javax.swing.JTextArea();
        txtKlas = new javax.swing.JTextField();
        lblDatabase = new javax.swing.JLabel();
        txtNaam = new javax.swing.JTextField();
        txtJaar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdToLog = new javax.swing.JButton();
        btnAdToLog1 = new javax.swing.JButton();
        txtLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        bntSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        NoordPaneel.setBackground(new java.awt.Color(0, 0, 0));
        NoordPaneel.setPreferredSize(new java.awt.Dimension(1127, 130));

        jTextField2.setBackground(new java.awt.Color(255, 255, 0));
        jTextField2.setText("jTextField1");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("DaBe");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 204));
        jLabel10.setText("Welcome,");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 204));
        jLabel11.setText("M0NK3Y5");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 204));
        jLabel12.setText("C0D3");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 204));
        jLabel14.setText("WH3N");

        lblUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 51, 255));
        lblUsername.setText("Welcome,");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Magneto", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Master of the MultiServer");

        javax.swing.GroupLayout NoordPaneelLayout = new javax.swing.GroupLayout(NoordPaneel);
        NoordPaneel.setLayout(NoordPaneelLayout);
        NoordPaneelLayout.setHorizontalGroup(
            NoordPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoordPaneelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(NoordPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(NoordPaneelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(NoordPaneelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addGap(24, 24, 24))
            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        NoordPaneelLayout.setVerticalGroup(
            NoordPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoordPaneelLayout.createSequentialGroup()
                .addGroup(NoordPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NoordPaneelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(NoordPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NoordPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(lblUsername))
                            .addComponent(jLabel6))
                        .addGroup(NoordPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NoordPaneelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(12, 12, 12))
                            .addGroup(NoordPaneelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(NoordPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(NoordPaneelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(NoordPaneel, java.awt.BorderLayout.PAGE_START);

        ZuidPaneel.setBackground(new java.awt.Color(0, 0, 0));

        lblUur.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        lblUur.setForeground(new java.awt.Color(255, 255, 0));
        lblUur.setText("jLabel1");

        jTextField1.setBackground(new java.awt.Color(255, 255, 0));
        jTextField1.setText("jTextField1");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 153));
        jLabel7.setText("ZOTTEGEM");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("WASHINGTON D.C.");

        lblUur1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        lblUur1.setForeground(new java.awt.Color(255, 255, 0));
        lblUur1.setText("jLabel1");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 153));
        jLabel9.setText("AR RAQQAH");

        lblUur2.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        lblUur2.setForeground(new java.awt.Color(255, 255, 0));
        lblUur2.setText("jLabel1");

        javax.swing.GroupLayout ZuidPaneelLayout = new javax.swing.GroupLayout(ZuidPaneel);
        ZuidPaneel.setLayout(ZuidPaneelLayout);
        ZuidPaneelLayout.setHorizontalGroup(
            ZuidPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZuidPaneelLayout.createSequentialGroup()
                .addGroup(ZuidPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZuidPaneelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZuidPaneelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUur1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)))
                .addGroup(ZuidPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ZuidPaneelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7))
                    .addComponent(lblUur, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(ZuidPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZuidPaneelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblUur2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ZuidPaneelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)))
                .addGap(127, 127, 127))
        );
        ZuidPaneelLayout.setVerticalGroup(
            ZuidPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZuidPaneelLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(ZuidPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZuidPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ZuidPaneelLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblUur1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZuidPaneelLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblUur2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZuidPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ZuidPaneelLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblUur))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZuidPaneelLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(32, 32, 32))))
                .addContainerGap())
        );

        jPanel1.add(ZuidPaneel, java.awt.BorderLayout.PAGE_END);

        RechtsPaneel.setBackground(new java.awt.Color(0, 0, 0));

        txtServer.setBackground(new java.awt.Color(0, 0, 0));
        txtServer.setColumns(20);
        txtServer.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtServer.setForeground(new java.awt.Color(255, 102, 102));
        txtServer.setRows(5);
        jScrollPane2.setViewportView(txtServer);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Server :");

        btnStartServer.setBackground(new java.awt.Color(0, 0, 255));
        btnStartServer.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnStartServer.setForeground(new java.awt.Color(255, 255, 255));
        btnStartServer.setText("Start server");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RechtsPaneelLayout = new javax.swing.GroupLayout(RechtsPaneel);
        RechtsPaneel.setLayout(RechtsPaneelLayout);
        RechtsPaneelLayout.setHorizontalGroup(
            RechtsPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RechtsPaneelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RechtsPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(RechtsPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        RechtsPaneelLayout.setVerticalGroup(
            RechtsPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RechtsPaneelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jPanel1.add(RechtsPaneel, java.awt.BorderLayout.LINE_END);

        CenterPaneel.setBackground(new java.awt.Color(0, 0, 0));
        CenterPaneel.setPreferredSize(new java.awt.Dimension(927, 550));

        txtDatabase.setBackground(new java.awt.Color(0, 0, 0));
        txtDatabase.setColumns(20);
        txtDatabase.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtDatabase.setForeground(new java.awt.Color(204, 204, 0));
        txtDatabase.setRows(5);
        jScrollPane1.setViewportView(txtDatabase);

        txtKlas.setBackground(new java.awt.Color(51, 51, 51));
        txtKlas.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        txtKlas.setForeground(new java.awt.Color(255, 255, 255));
        txtKlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKlasActionPerformed(evt);
            }
        });

        lblDatabase.setBackground(new java.awt.Color(0, 0, 0));
        lblDatabase.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lblDatabase.setForeground(new java.awt.Color(255, 255, 255));
        lblDatabase.setText("Database :");

        txtNaam.setBackground(new java.awt.Color(51, 51, 51));
        txtNaam.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        txtNaam.setForeground(new java.awt.Color(255, 255, 255));
        txtNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaamActionPerformed(evt);
            }
        });

        txtJaar.setBackground(new java.awt.Color(51, 51, 51));
        txtJaar.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        txtJaar.setForeground(new java.awt.Color(255, 255, 255));
        txtJaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJaarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Naam:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Klas :");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Geboortejaar :");

        btnAdToLog.setBackground(new java.awt.Color(0, 0, 255));
        btnAdToLog.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnAdToLog.setForeground(new java.awt.Color(255, 255, 255));
        btnAdToLog.setText("Add to Log");
        btnAdToLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdToLogActionPerformed(evt);
            }
        });

        btnAdToLog1.setBackground(new java.awt.Color(0, 0, 255));
        btnAdToLog1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnAdToLog1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdToLog1.setText("Save Log");
        btnAdToLog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdToLog1ActionPerformed(evt);
            }
        });

        txtLocation.setBackground(new java.awt.Color(51, 51, 51));
        txtLocation.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(255, 255, 255));
        txtLocation.setText("Database.csv");
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Save locatie :");

        lblResult.setBackground(new java.awt.Color(0, 0, 0));
        lblResult.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 0));

        bntSearch.setBackground(new java.awt.Color(0, 0, 255));
        bntSearch.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        bntSearch.setForeground(new java.awt.Color(255, 255, 255));
        bntSearch.setText("Search");
        bntSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CenterPaneelLayout = new javax.swing.GroupLayout(CenterPaneel);
        CenterPaneel.setLayout(CenterPaneelLayout);
        CenterPaneelLayout.setHorizontalGroup(
            CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterPaneelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CenterPaneelLayout.createSequentialGroup()
                        .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(CenterPaneelLayout.createSequentialGroup()
                                .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CenterPaneelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(95, 95, 95))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenterPaneelLayout.createSequentialGroup()
                                        .addComponent(txtKlas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJaar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdToLog, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblDatabase)
                    .addGroup(CenterPaneelLayout.createSequentialGroup()
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdToLog1))
                    .addComponent(lblResult)
                    .addComponent(jScrollPane1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        CenterPaneelLayout.setVerticalGroup(
            CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterPaneelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatabase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenterPaneelLayout.createSequentialGroup()
                        .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CenterPaneelLayout.createSequentialGroup()
                                .addComponent(btnAdToLog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdToLog1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenterPaneelLayout.createSequentialGroup()
                        .addGroup(CenterPaneelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJaar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)))
                .addGap(78, 78, 78)
                .addComponent(lblResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(CenterPaneel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKlasActionPerformed

    private void txtNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaamActionPerformed

    private void txtJaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJaarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJaarActionPerformed

    private void btnAdToLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdToLogActionPerformed
       
     
        naam =  txtNaam.getText();
        //textveld naam is verplicht anders krijgt mijn lege records in de database
        if(!naam.equals(""))
        {
       	klas =  txtKlas.getText();
        jaar = txtJaar.getText();
        Gegevens  tempGegevens = new Gegevens (naam, klas, jaar); 
     		
     	// voeg dit object toe aan de lijst
     	lijst.add (tempGegevens);
        
        String tabNaam;
        String tabKlas;
                      
        // de header maken en dan de arraylist doorlopen en dan nieuwe toevoegen
        // dit laat ook toe om na een opzoeking + nieuwe toevoeging de database lijst zien (ipv een gemixte lijst)
        txtDatabase.setText("Naam" + "\t" + "Klas" + "\t" + "Jaar" + "\n" + "====" + "\t" + "====" + "\t" + "====" );
        int iCount = 0;
        for(Gegevens tekst: lijst) 
        {
            iCount++;
            txtDatabase.setText(txtDatabase.getText() + "\n" +tekst.getNaam() +"\t" + tekst.getKlas() + "\t"  + tekst.getJaar());
            
        }
        
        lblDatabase.setText("Database : " + iCount + " record(s) in total");
        
        
        
        
        
       // niet vergeten (indien nodig) :
       // validate();
        repaint();
        
        
        txtKlas.setText("");
        txtJaar.setText("");
        //naam als laatste=>focus
        txtNaam.setText("");
        txtNaam.requestFocusInWindow();
        }
        else
        {
            int ii;
            for (ii=0;ii<3900;ii++)
            {
            Graphics2D g99 = (Graphics2D) getGraphics();
            g99.setFont(new Font("OCR A Extended", Font.PLAIN, 28));
            g99.setColor(Color.RED);
            g99.drawString("You haven't entered a name.", 350, 680);
            g99.drawRect(190, 655,740,35);
            }
            
            
            txtNaam.requestFocusInWindow();
            
        }
        
    }//GEN-LAST:event_btnAdToLogActionPerformed

    private void btnAdToLog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdToLog1ActionPerformed
        // TODO add your handling code here:
        
    BufferedWriter uit;
			
    try {  
        String bestandnaam = txtLocation.getText();  
        uit = new BufferedWriter( new FileWriter( bestandnaam ,true) );

        for(Gegevens tekst: lijst) 
        {
            uit.write("" + tekst );        
            uit.newLine();
	}	
      uit.close();   
   
      	Calendar cd; 
	cd = Calendar.getInstance();
        int uren = cd.get(Calendar.HOUR_OF_DAY); 
        int minuten = cd.get(Calendar.MINUTE); 
        int seconden = cd.get(Calendar.SECOND);
        lblResult.setText("<html>Bestand <b><i>" + bestandnaam + " </i></b>werd aangemaakt om " +  String.format("%02d", uren) + 
                ":"+ String.format("%02d", minuten) + ":"+ String.format("%02d", seconden)+"</html>");
        
            int ii;
            for (ii=0;ii<3900;ii++)
            {
            Graphics2D g99 = (Graphics2D) getGraphics();
            g99.setFont(new Font("OCR A Extended", Font.PLAIN, 24));
            g99.setColor(Color.CYAN);
            g99.drawString("Bestand " + bestandnaam + " werd aangemaakt om " +  String.format("%02d", uren) + 
                ":"+ String.format("%02d", minuten) + ":"+ String.format("%02d", seconden), 200, 680);
            g99.drawRect(190, 655,740,35);
            
            }
        txtNaam.requestFocusInWindow();
 
        }
        catch( IOException ee ) {
            Graphics2D g99 = (Graphics2D) getGraphics();
            g99.setFont(new Font("OCR A Extended", Font.PLAIN, 24));
            g99.setColor(Color.CYAN);
            g99.drawString("Fout bij het openen, maken of sluiten bestand", 200, 680);
            ee.printStackTrace();
 
        }
        repaint();
        
        
    }//GEN-LAST:event_btnAdToLog1ActionPerformed

    
         // slaap routine, schrappen indien niet gebruikt
  public static void slaap (int millseconds){		 
		try {
			Thread.sleep(millseconds); 
		} catch (InterruptedException e){ }
	} 
  
  
    
    
    
    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void bntSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSearchActionPerformed
        // TODO add your handling code here:
        String resultaat;
        resultaat = "";
        if (txtNaam.getText().equals("") && txtKlas.getText().equals("") && txtJaar.getText().equals(""))
        {
            
            int ii;
            for (ii=0;ii<3900;ii++)
            {
            Graphics2D g99 = (Graphics2D) getGraphics();
            //g99.setColor(Color.RED);
            g99.setFont(new Font("OCR A Extended", Font.PLAIN, 24));
            //g99.fillRect(124, 660, 300, 30);
            g99.setColor(Color.RED);
            g99.drawString("You haven't entered a search value", 300, 680);
            g99.drawRect(190, 655,740,35);
            
            }
        }
        int iCount=0;
                for(Gegevens tekst: lijst) 
        {
                boolean contains = false;
                double percent = 0.0;
                if (tekst.getNaam().equalsIgnoreCase(txtNaam.getText()))
                {
                  percent = percent + 33.33; 
                  contains = true;
                } 
                if (tekst.getKlas().equalsIgnoreCase(txtKlas.getText()))
                {
                  percent = percent + 33.33; 
                  contains = true;
                } 
                if (tekst.getJaar().equalsIgnoreCase(txtJaar.getText()))
                {
                  percent = percent + 33.33; 
                  contains = true;
                } 
                if (percent==99.99)
                        {
                            percent = 100;
                        }
                if(contains)
                {
                    iCount++;
                    resultaat = resultaat + "\n" + tekst.getNaam() +"\t" + tekst.getKlas() + "\t"  + tekst.getJaar() +"\t" + "Match = " + percent + "%";
                }
	}
                
        txtDatabase.setText("Naam" + "\t" + "Klas" + "\t" + "Jaar" + "\n" + "====" + "\t" + "====" + "\t" + "====" + resultaat);   
        lblDatabase.setText("Database : " + iCount + " record(s) found with search");
        
        txtNaam.requestFocusInWindow();
        
        
    }//GEN-LAST:event_bntSearchActionPerformed

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        kms = new KKMultiServer(txtServer);      
        kms.start();
    }//GEN-LAST:event_btnStartServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MijnVenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MijnVenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MijnVenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MijnVenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MijnVenster().setVisible(true);
            }
        });
    }
        
    private Klokske klokje;
    private KKMultiServer kms ;
    private String naam, klas, jaar;
    private ArrayList<Gegevens> lijst;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPaneel;
    private javax.swing.JPanel NoordPaneel;
    private javax.swing.JPanel RechtsPaneel;
    private javax.swing.JPanel ZuidPaneel;
    private javax.swing.JButton bntSearch;
    private javax.swing.JButton btnAdToLog;
    private javax.swing.JButton btnAdToLog1;
    private javax.swing.JButton btnStartServer;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblDatabase;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUur;
    private javax.swing.JLabel lblUur1;
    private javax.swing.JLabel lblUur2;
    private javax.swing.JTextArea txtDatabase;
    private javax.swing.JTextField txtJaar;
    private javax.swing.JTextField txtKlas;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtNaam;
    private javax.swing.JTextArea txtServer;
    // End of variables declaration//GEN-END:variables


 class Klokske extends Thread {
  	
    // geen constructor nodig --> automatic default constructor
  	
  	public void run(){
            
            
  	  while (true){

             Graphics2D g1 = (Graphics2D) getGraphics();
            g1.setColor(Color.DARK_GRAY);
            g1.drawOval(510, 723, 100, 100); 
            g1.setColor(Color.DARK_GRAY);
            g1.drawOval(190, 723, 100, 100); 
            g1.setColor(Color.DARK_GRAY);
            g1.drawOval(810, 723, 100, 100); 
            
//             Graphics2D g = (Graphics2D) getGraphics();
//            g.setColor(Color.YELLOW);
//            g.drawOval(700, 680, 150, 150); 
           
            
            
              
		Calendar cd; 
		cd = Calendar.getInstance();
                //local time
                int uren = cd.get(Calendar.HOUR_OF_DAY); 
                int minuten = cd.get(Calendar.MINUTE); 
                int seconden = cd.get(Calendar.SECOND);
		lblUur.setText("" + String.format("%02d", uren) + ":"+ String.format("%02d", minuten) + ":"+ String.format("%02d", seconden)) ;
                //Washington time
                int urenW = uren -6;
                if(urenW < 0) 
                {
                    urenW = urenW+ 24;
                }
                //ArRaqqah time
                  int urenR = uren + 1;
                if(urenR > 23) 
                {
                    urenR = urenR -  24;
                }
                              
                lblUur1.setText("" + String.format("%02d", urenW) + ":"+ String.format("%02d", minuten) + ":"+ String.format("%02d", seconden)) ;
                
                lblUur2.setText("" + String.format("%02d", urenR) + ":"+ String.format("%02d", minuten) + ":"+ String.format("%02d", seconden)) ;
                
            g1.setColor(Color.MAGENTA);
            g1.drawRect(250, 57,716,60);
            g1.setColor(Color.blue);
            g1.drawRect(252, 59,712,56);
            g1.setColor(Color.lightGray);
            g1.drawRect(254, 61,708,52);   
                
//            g1.setColor(Color.RED);
//            g1.drawRect(250, 57,740,60);
//            g1.setColor(Color.ORANGE);
//            g1.drawRect(252, 59,736,56);
//            g1.setColor(Color.PINK);
//            g1.drawRect(254, 61,732,52);
                
            g1.setColor(Color.WHITE);
            g1.fillArc(510, 723, 100, 100,90 - (30 * uren),3)  ;
            g1.setColor(Color.BLUE);
            g1.fillArc(510, 723, 100, 100,90 - (6*minuten),3)  ;
            g1.setColor(Color.YELLOW);
            g1.fillArc(510, 723, 100, 100,90 - (6*seconden),3)  ;  
            g1.setColor(Color.WHITE);
            g1.fillArc(190, 723, 100, 100,90 - (30*(urenW)),3)  ; 
            g1.setColor(Color.BLUE);
            g1.fillArc(190, 723, 100, 100,90 - (6*minuten),3)  ; 
            g1.setColor(Color.YELLOW);
            g1.fillArc(190, 723, 100, 100,90 - (6*seconden),3)  ; 
            g1.setColor(Color.WHITE);
            g1.fillArc(810, 723, 100, 100,90 - (30*(urenR)),3)  ;
            g1.setColor(Color.BLUE);
            g1.fillArc(810, 723, 100, 100,90 - (6*minuten),3)  ; 
            g1.setColor(Color.YELLOW);
            g1.fillArc(810, 723, 100, 100,90 - (6*seconden),3)  ;                  
                
                
                
                                       
        repaint();
  	  }
  	  
  	}

}
}


  	class Gegevens {
    // attributen
	private String naam ;
	private String klas ;
	private String jaar ;    // enz voor méér gegevens .... zelf uitbreiden
	
	// Constructor
	public Gegevens ( String naam, String klas, String jaar ){
		this.naam = naam;
		this.klas = klas;
		this.jaar = jaar;
	}
	

	public void setNaam (String naam){
		this.naam = naam;
	}
	public String getNaam(){
		return naam;
	}

	public void setKlas (String klas){
		this.klas = klas;
	}
	public String getKlas(){
		return klas;
	}

	public void setJaar (String jaar){
		this.jaar = jaar;
	}
	public String getJaar(){
		return jaar;
	}	
	// toString() methode, volstaat voorlopig om de gegevens zichtbaar te maken
	public String toString(){
		//String tekst = String.format ("" , naam, klas, jaar);
		String tekst = ("" + naam + "," + klas + "," + jaar);
		return tekst;
	}
        }


